name: Release Multi-Arch Linux Binary

on:
  push:
    tags:
      - 'v*' # Trigger only on version tags, e.g., v1.0.0
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.2.3)'
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Build ${{ matrix.arch }} binary
        run: |
          make release-build ARCH=${{ matrix.arch }}

      - name: Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: bin/fwtui-${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}